//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarOptional
    {
        public int Id { get; set; }
        public int IdCar { get; set; }
        public int IdOptional { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Optional Optional { get; set; }
    }
}
