//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CatDBEntities : DbContext
    {
        public CatDBEntities()
            : base("name=CatDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Car> Car { get; set; }
        public virtual DbSet<Optional> Optional { get; set; }
        public virtual DbSet<CarOptional> CarOptional { get; set; }
    
        public virtual ObjectResult<GetAllCars_Result> GetAllCars()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllCars_Result>("GetAllCars");
        }
    }
}
